# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0002_auto_20170531_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
                ('Chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chating.Chat')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chating.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='chating.Membership', to='chating.Chat'),
        ),
    ]
