# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-03 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0003_auto_20170603_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='Chat',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='chat',
            field=models.ManyToManyField(to='chating.Chat'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
