# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0006_auto_20170603_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='chat',
            field=models.ManyToManyField(blank=True, to='chating.Chat'),
        ),
    ]
