# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-03 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0007_auto_20170603_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='chat',
        ),
    ]
