# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0010_auto_20170603_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='chat',
            field=models.ManyToManyField(blank=True, to='chating.Chat'),
        ),
    ]
