# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdetails_mobile_no'),
        ('chating', '0012_auto_20170604_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.AddField(
            model_name='group',
            name='user_details',
            field=models.ManyToManyField(blank=True, to='accounts.UserDetails'),
        ),
    ]
