# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chating', '0013_auto_20170604_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user_details',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
