# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_friendship_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
