# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-12 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_posts_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='to_friend_wall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_friend_wall_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
