# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
