# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdetails_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('user_details', models.ManyToManyField(blank=True, to='accounts.UserDetails')),
            ],
        ),
    ]
