# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user_details',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='group',
            field=models.ManyToManyField(blank=True, to='accounts.Group'),
        ),
    ]
