# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('accounts', '0009_remove_group_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('chat', models.ManyToManyField(blank=True, to='accounts.Chats')),
            ],
            bases=('auth.group',),
        ),
        migrations.RemoveField(
            model_name='group',
            name='chat',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
