# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_extendgroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendgroup',
            name='user',
        ),
    ]
